export const ROLE_OPTIONS = [
  "Software Engineer",
  "Senior Software Engineer",
  "Staff Software Engineer",
  "Frontend Engineer",
  "Backend Engineer",
  "Full-Stack Engineer",
  "Mobile Engineer",
  "DevOps Engineer",
  "Site Reliability Engineer",
  "Data Engineer",
  "Data Scientist",
  "Data Analyst",
  "Machine Learning Engineer",
  "Product Manager",
  "Senior Product Manager",
  "Product Designer",
  "Senior Product Designer",
  "UX Designer",
  "UX Researcher",
  "Design Lead",
  "Design Systems Engineer",
  "Engineering Manager",
  "Technical Program Manager",
  "Project Manager",
  "QA Engineer",
  "Security Engineer",
  "Solutions Architect",
  "Sales Engineer",
  "Account Executive",
  "Customer Success Manager",
  "Marketing Manager",
  "Growth Marketer",
  "Content Strategist",
  "Business Analyst",
  "Operations Manager",
  "Finance Analyst",
  "Recruiter",
  "HR Business Partner",
  "Founder",
  "Chief of Staff",
];

export const LOCATION_OPTIONS = [
  "Remote — anywhere",
  "Remote — US",
  "Remote — EMEA",
  "Remote — APAC",
  "Remote — LatAm",
  "Nairobi, Kenya",
  "Lagos, Nigeria",
  "Cairo, Egypt",
  "Cape Town, South Africa",
  "London, UK",
  "Berlin, Germany",
  "Amsterdam, Netherlands",
  "Dublin, Ireland",
  "Paris, France",
  "Lisbon, Portugal",
  "New York, US",
  "San Francisco, US",
  "Austin, US",
  "Seattle, US",
  "Toronto, Canada",
  "Bengaluru, India",
  "Singapore",
  "Dubai, UAE",
  "Tel Aviv, Israel",
  "Sydney, Australia",
];
