"use client";

import { useRouter } from "next/navigation";
import { useState, useTransition, type FormEvent } from "react";
import { Chip } from "@/components/Chip";
import { discardApplication, regenerateDraft, updateApplicationDraft } from "@/lib/actions";
import type { ApplicationWithOpening } from "@/lib/types";

const NUDGES = ["Plainer", "Shorter", "Warmer", "More technical"];

export function DraftReview({ applications }: { applications: ApplicationWithOpening[] }) {
  const router = useRouter();
  const [index, setIndex] = useState(0);
  const [editing, setEditing] = useState(false);
  const [isPending, startTransition] = useTransition();
  const app = applications[Math.min(index, applications.length - 1)];
  const failed = Boolean(app.draft_text?.startsWith("Draft generation failed"));
  const waiting = !app.draft_text;
  const paragraphs = (app.draft_text ?? "").split(/\n{2,}/).filter(Boolean);

  function next() { setEditing(false); if (index >= applications.length - 1) router.push("/send"); else setIndex((value) => value + 1); }
  function skip() { startTransition(async () => { await discardApplication(app.id); router.refresh(); }); }
  function regenerate(tone?: string) { startTransition(async () => { await regenerateDraft(app.id, tone ?? ""); router.refresh(); }); }
  function saveEdit(event: FormEvent<HTMLDivElement>) { updateApplicationDraft(app.id, event.currentTarget.innerText.trim()); setEditing(false); }

  return <div className="flex min-h-0 flex-1 flex-col bg-paper"><div className="flex items-center justify-between border-b border-border bg-white px-7 py-4"><div><div className="text-[11px] font-bold uppercase tracking-[.16em] text-accent">Draft review</div><div className="mt-1 text-[15px] font-semibold">{applications.length} draft{applications.length === 1 ? "" : "s"} in queue</div><div className="mt-1 text-[11px] text-muted">Drafts prepare in the background. Nothing is sent without your approval.</div></div><div className="flex gap-2.5"><button type="button" onClick={skip} disabled={isPending} className="rounded-xl border border-border-strong px-3.5 py-2.5 text-[12px] font-medium">Remove</button><button type="button" onClick={next} disabled={isPending || waiting} className="rounded-xl bg-accent px-4 py-2.5 text-[12px] font-semibold text-white">{index === applications.length - 1 ? "Review approval →" : "Next draft →"}</button></div></div>
    <div className="grid min-h-0 flex-1 grid-cols-[270px_minmax(0,1fr)_330px] gap-0"><aside className="border-r border-border bg-white p-4"><div className="mb-3 text-[11px] font-bold uppercase tracking-[.12em] text-faint">Queue</div><div className="flex flex-col gap-2">{applications.map((item, itemIndex) => <button type="button" key={item.id} onClick={() => { setIndex(itemIndex); setEditing(false); }} className={`rounded-xl border p-3 text-left ${itemIndex === index ? "border-accent bg-accent-tint" : "border-border bg-white"}`}><div className="truncate text-[12px] font-bold">{item.opening.title}</div><div className="mt-1 truncate text-[11px] text-muted">{item.opening.company}</div><div className="mt-2 text-[10px] font-semibold text-faint">{item.draft_text && !item.draft_text.startsWith("Draft generation failed") ? "Ready to review" : "Needs retry"}</div></button>)}</div></aside>
      <main className="min-h-0 overflow-y-auto px-8 py-7"><div className="mx-auto max-w-[620px]"><div className="mb-5 flex items-start justify-between gap-4"><div><div className="text-[11px] font-bold uppercase tracking-[.12em] text-faint">Application {index + 1} of {applications.length}</div><h1 className="mt-2 text-[24px] font-semibold tracking-[-.04em]">{app.opening.title}</h1><div className="mt-1 text-[13px] text-muted">{app.opening.company} · {app.opening.location ?? "Location not listed"}</div></div><span className="rounded-full bg-good-tint px-3 py-1.5 text-[11px] font-bold text-good">{app.opening.fit_score ?? "—"}% fit</span></div>{waiting ? <div className="mt-5 rounded-2xl border border-accent/20 bg-accent-tint p-6"><div className="text-[14px] font-semibold text-accent">Preparing this draft…</div><p className="mt-2 text-[12px] leading-relaxed text-muted">You can stay here. The draft will appear automatically when it is ready.</p></div> : failed ? <div className="rounded-2xl border border-warn-border bg-warn-tint-soft p-5"><div className="text-[14px] font-semibold">This draft needs another try</div><p className="mt-2 text-[12px] leading-relaxed text-muted">The job is still in your queue. Regenerate it or write directly below; no application was sent.</p><button type="button" onClick={() => regenerate()} disabled={isPending} className="mt-4 rounded-xl bg-accent px-4 py-2.5 text-[12px] font-bold text-white">{isPending ? "Generating…" : "Generate this draft"}</button></div> : null}{!waiting && <><div className={`mt-5 min-h-[430px] border bg-white p-9 text-[13px] leading-[1.8] text-[#3D3C36] outline-none ${editing ? "border-accent" : "border-border"}`} contentEditable={editing} suppressContentEditableWarning onBlur={editing ? saveEdit : undefined}><div className="text-[11px] leading-relaxed text-faint">Application for {app.opening.title} at {app.opening.company}</div><div className="my-3.5 h-px bg-border"/>{paragraphs.length > 0 ? paragraphs.map((paragraph, paragraphIndex) => <p key={paragraphIndex} className={paragraphIndex > 0 ? "mt-3.5" : ""}>{paragraph}</p>) : <p className="text-faint">Write your own draft here while AI is unavailable.</p>}<div className="mt-4">{app.signoff}</div></div><div className="mt-3 flex justify-end"><button type="button" onClick={() => setEditing((value) => !value)} className="rounded-xl border border-border-strong px-3.5 py-2 text-[12px] font-semibold">{editing ? "Save edit" : "Edit this draft"}</button></div></>}</div></main>
      <aside className="min-h-0 overflow-y-auto border-l border-border bg-white p-5"><div className="text-[11px] font-bold uppercase tracking-[.12em] text-faint">Job context</div><div className="mt-3 rounded-xl bg-paper p-3"><div className="text-[12px] font-bold">{app.opening.title}</div><div className="mt-1 text-[11px] text-muted">{app.opening.company}</div><div className="mt-3 max-h-40 overflow-y-auto whitespace-pre-wrap text-[11px] leading-relaxed text-muted">{app.opening.description}</div></div><div className="mt-5 text-[11px] font-bold uppercase tracking-[.12em] text-faint">Human voice</div><div className="mt-3 flex flex-col gap-2 text-[12px] leading-relaxed text-muted"><div>✓ Grounded in your résumé</div><div>✓ No invented claims</div><div>✓ Written for this job, not a template</div></div>{app.draft_highlight && <div className="mt-5 rounded-xl bg-good-tint p-3 text-[11px] leading-relaxed text-good"><strong>Specific detail:</strong> {app.draft_highlight}</div>}<div className="mt-6 text-[12px] font-semibold">Tune the voice</div><div className="mt-2 flex flex-wrap gap-1.5">{NUDGES.map((label) => <Chip key={label} variant="tag" className="rounded-full !px-3 !py-2 text-[11.5px]" disabled={isPending} onClick={() => regenerate(label)}>{label}</Chip>)}</div></aside>
    </div></div>;
}
